### ISSUE TITLE
Loading Fantomas projects cause client side LSP server to stop responding.

### ISSUE THREAD

**Issue by TheAngryByrd** [ionide/LanguageServerProtocol#36]
**Describe the bug**

When loading [Fantomas](https://github.com/fsprojects/fantomas) it seems to get stuck on Project Loading.

<img width="386" alt="Screen Shot 2022-09-11 at 5 53 36 PM" src="https://user-images.githubusercontent.com/1490044/189550431-7edc7f79-e2ce-49c0-b62f-48bb3506d227.png">

In the dev tools we get:

```

$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
mainThreadExtensionService.ts:79 [[object Object]]Header must provide a Content-Length property.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 Error: Header must provide a Content-Length property.
	at StreamMessageReader.onData (/Users/theangrybyrd/Repositories/public/ionide-vscode-fsharp/release/fsharp.js:15408:27)
	at Socket.<anonymous> (/Users/theangrybyrd/Repositories/public/ionide-vscode-fsharp/release/fsharp.js:15392:18)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
	at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
```

It's unclear as to exactly why.  It's suspected [this custom write code](https://github.com/ionide/LanguageServerProtocol/blob/2414bd33c29f2530ae465021b1016fdb510b48ee/src/LanguageServerProtocol.fs#L386-L396) is to blame.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Fantomas in vscode
2. It doesn't seem to load.

**Expected behaviour**

Fantomas loads.

**Screenshots**

**Environment (please complete the following information):**

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.303 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
  ```

**Comment by TheAngryByrd** [comment]
I can't seem to reproduce this now, closing.
